### ISSUE TITLE
Sanitize removed from Rails 5.1.1

### ISSUE THREAD

**Issue by Svashta** [csm123/starburst#16]
Hi,

i am trying to update my app to Rails 5.1.1 - but announcement seems to be using "sanitize" which is removed from 5.1.1 - and I am getting errors.

Is it possible you change this so that the gem can work with 5.1.1?

Thx

**Comment by weverwijk** [comment]
#18 Pull request is created.

**Comment by rogermarlow** [comment]
Hi, this was merged to master but is it likely to make it into a new gem version on rubygems.org? The latest version up there is 1.0.3 from Mar 14,2015. To get this fix I am having to reference this repo direct from my Gemfile.
Thanks, Roger.
