### ISSUE TITLE
Error when dismissing Announcement

### ISSUE THREAD

**Issue by IGPython** [csm123/starburst#6]
Seems that we get a missing field error from Post Gres

PG::UndefinedColumn: ERROR:  column starburst_announcement_views.user does not exist
LINE 1: ...ews".* FROM "starburst_announcement_views"  WHERE "starburst...
                                                             ^
: SELECT  "starburst_announcement_views".* FROM "starburst_announcement_views"  WHERE "starburst_announcement_views"."user" = 7 AND "starburst_announcement_views"."announcement" = 12 LIMIT 1
Completed 500 Internal Server Error in 19ms

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column starburst_announcement_views.user does not exist
LINE 1: ...ews".* FROM "starburst_announcement_views"  WHERE "starburst...

I assume its the controller needs updating as teh field name is user_id not user?

**Comment by csm123** [comment]
Fixed in a26007757b69c095e400acb20e0b30229559513d

Will release next version as a gem in a bit

**Comment by csm123** [comment]
Pushed as v1.0.3 - on rubygems so feel free to update the gem in your gemfile. Thank you for reporting this.
